// Importing necessary functions from Redux Toolkit
import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  isLoggedIn: false,
};

// Creating a slice
const exampleSlice = createSlice({
  name: "example", // Name of the slice
  initialState, // Initial state defined above
  reducers: {
    changeLoggedInStatus: (state, action) => {
      state.isLoggedIn = action.payload;
    },
  },
});

// Exporting the actions generated by createSlice
export const { changeLoggedInStatus } = exampleSlice.actions;

// Exporting the reducer to be used in the store
export default exampleSlice.reducer;
